<a href="https://colab.research.google.com/github/shiv-coder/AIDI1002W2026/blob/main/Module11.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:

#Step 1 — Load Dataset and Preview
import pandas as pd
from sklearn.model_selection import train_test_split

# TODO 1: Load dataset
from google.colab import files
uploaded = files.upload()
df = pd.read_csv(list(uploaded.keys())[0])
# Preview first 5 rows
print(df.head())

Saving Week11_Student_data.csv to Week11_Student_data.csv
   HoursStudied  AssignmentsCompleted  AttendancePercentage  SleepHours  \
0             2                     1                    60           5   
1             3                     2                    65           6   
2             4                     2                    70           6   
3             5                     3                    75           7   
4             6                     3                    80           7   

   PreviousScore  InternetUsageHours  ExamScore  
0             48                   4         50  
1             52                   3         55  
2             55                   3         60  
3             60                   2         65  
4             65                   2         70  


In [6]:

# Define features (X) and target (y)
X = df[['HoursStudied', 'AssignmentsCompleted']].values
y = df['ExamScore'].values.reshape(-1, 1)

In [7]:
#Part 2 — Activation Functions
# Sigmoid function
import numpy as np
def sigmoid(x):
    # TODO 3
    return 1 / (1 + np.exp(-x))

# ReLU function
def relu(x):
    # TODO 4
    return np.maximum(0, x)

# TODO 5: Test functions
sample = np.array([-2, -1, 0, 1, 2])

print("Sigmoid:", sigmoid(sample))
print("ReLU:", relu(sample))

Sigmoid: [0.11920292 0.26894142 0.5        0.73105858 0.88079708]
ReLU: [0 0 0 1 2]


In [8]:
#Part 3 — Simple Neural Network (1 Hidden Layer)
# TODO 6: Initialize random weights
np.random.seed(0)

input_size = 2
hidden_size = 3
output_size = 1

W1 = np.random.rand(input_size, hidden_size)
b1 = np.random.rand(1, hidden_size)

W2 = np.random.rand(hidden_size, output_size)
b2 = np.random.rand(1, output_size)

# TODO 7 & 8: Forward propagation
# Hidden layer
z1 = np.dot(X, W1) + b1
a1 = relu(z1)

# Output layer
z2 = np.dot(a1, W2) + b2
output = sigmoid(z2)

# TODO 9: Compare predicted vs actual
print("Predicted Output:\n", output[:5])
print("Actual Output:\n", y[:5])

Predicted Output:
 [[0.99349364]
 [0.99909789]
 [0.99969817]
 [0.99995838]
 [0.99998608]]
Actual Output:
 [[50]
 [55]
 [60]
 [65]
 [70]]


In [9]:
#Part 4 — Functional Programming
# TODO 10: Add 5 bonus points to ExamScore
bonus_scores = list(map(lambda x: x + 5, df['ExamScore']))
print("Bonus Scores:", bonus_scores[:5])

# TODO 11: Filter students with ExamScore >= 75
high_scores = list(filter(lambda x: x >= 75, df['ExamScore']))
print("High Scores:", high_scores[:5])

# TODO 12: Square HoursStudied
squared_hours = list(map(lambda x: x**2, df['HoursStudied']))
print("Squared Hours:", squared_hours[:5])

Bonus Scores: [55, 60, 65, 70, 75]
High Scores: [75, 80, 85, 90, 77]
Squared Hours: [4, 9, 16, 25, 36]


In [10]:
#Part 5 — Combine Neural Network with Functional Programming
# TODO 13: Normalize features using functional programming

# Normalize HoursStudied (divide by max)
max_hours = max(df['HoursStudied'])
norm_hours = list(map(lambda x: x / max_hours, df['HoursStudied']))

# Normalize AssignmentsCompleted
max_assign = max(df['AssignmentsCompleted'])
norm_assign = list(map(lambda x: x / max_assign, df['AssignmentsCompleted']))

# Combine normalized features
X_norm = np.array(list(zip(norm_hours, norm_assign)))

# Run through neural network again
z1 = np.dot(X_norm, W1) + b1
a1 = relu(z1)

z2 = np.dot(a1, W2) + b2
output_norm = sigmoid(z2)

print("Output after normalization:\n", output_norm[:5])

Output after normalization:
 [[0.91276197]
 [0.9330538 ]
 [0.93958044]
 [0.95394894]
 [0.95852903]]
