<a href="https://colab.research.google.com/github/shiv-coder/AIDI1002W2026/blob/main/Module10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [27]:

#Step 1 — Load Dataset and Preview
import pandas as pd
from sklearn.model_selection import train_test_split

# TODO 1: Load dataset
from google.colab import files
uploaded = files.upload()
df = pd.read_csv(list(uploaded.keys())[0])
# Preview first 5 rows
print(df.head())

Saving Week10_Loan_dataset.csv to Week10_Loan_dataset (2).csv
   Age  Income  CreditScore  LoanAmount  LoanDuration  Approved
0   25   50000          650       20000             5         0
1   40   80000          720       15000             3         1
2   30   60000          680       25000             4         0
3   50  120000          750       20000             5         1
4   35   70000          690       18000             4         1


In [28]:
#Step 2 — Split Dataset into Training and Testing Sets
from sklearn.model_selection import train_test_split

# Features and target
X = df[["Age","Income","CreditScore","LoanAmount","LoanDuration"]]
y = df["Approved"]

# Split 80% train, 20% test
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

print("Training samples:", X_train.shape[0])
print("Testing samples:", X_test.shape[0])

Training samples: 16
Testing samples: 4


In [29]:
#Step 3 — Scale Features
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)
print(X_train_scaled)
print(X_test_scaled)

[[-0.89609192 -1.12183117 -1.15182919 -1.34715063 -1.34687429]
 [-1.04861821 -1.51309654 -1.7145549  -1.86035087 -1.34687429]
 [ 1.08674978  0.93231201  1.38043651  0.96225045  0.92154557]
 [ 2.30696006  2.39955714  1.94316222  0.70565033  2.05575549]
 [-0.43851307 -0.53493312 -0.30774062 -0.32075015 -0.21266436]
 [-1.35367078 -1.072923   -1.15182919 -1.34715063 -1.34687429]
 [-1.20114449 -0.92619849 -1.43319204 -0.83395039 -1.34687429]
 [-0.74356564 -0.53493312 -0.02637777  1.98865093  0.92154557]
 [ 0.47664464  0.68777116  0.53634794 -0.32075015 -0.21266436]
 [ 0.32411836  0.49213847  0.53634794  0.19245009 -0.21266436]
 [ 0.01906579 -0.04585141  0.25498509  0.19245009  0.92154557]
 [ 0.17159207  0.19868944  0.39566651  0.19245009  0.92154557]
 [-0.28598678 -0.29039227 -0.30774062  0.70565033 -0.21266436]
 [-0.59103935 -0.63274946 -0.58910348 -0.57735027 -0.21266436]
 [ 0.62917092  0.7855875   0.8177108   0.44905021 -0.21266436]
 [ 1.54432863  1.17685287  0.8177108   1.21885057  0.92

In [30]:
#Step 4 — Train Logistic Regression Classifier
from sklearn.linear_model import LogisticRegression

# Initialize model
model = LogisticRegression(max_iter=1000,C=0.1)

# Train model
model.fit(X_train_scaled, y_train)

# Predict on test set
y_pred = model.predict(X_test_scaled)
print("Predictions:", y_pred)

Predictions: [0 1 0 1]


Logistic Regression can “memorize” the training data if allowed → this is overfitting.

C is a parameter that controls regularization, which prevents overfitting.

C value	Effect
Large (e.g., 1000)	Weak regularization → model can memorize → overfit
Small (e.g., 0.1)	Strong regularization → model is simpler → generalizes better

In [31]:
#Step 5 — Confusion Matrix and Metrics
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score

# Confusion Matrix
cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:\n", cm)

# Key metrics
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)

print("Accuracy:", accuracy)
print("Precision:", precision)
print("Recall:", recall)
print("F1 Score:", f1)

Confusion Matrix:
 [[2 0]
 [0 2]]
Accuracy: 1.0
Precision: 1.0
Recall: 1.0
F1 Score: 1.0


Good model = high test accuracy + balanced precision/recall + stable CV scores

Overfitted model → very high train accuracy but low test accuracy

Underfitted model → low train and test accuracy

In [32]:
#Step 6 — K-Fold Cross Validation
from sklearn.model_selection import cross_val_score
import numpy as np

# 5-Fold CV on full dataset
cv_scores = cross_val_score(model, scaler.fit_transform(X), y, cv=5)

print("CV Scores:", cv_scores)
print("Mean CV Accuracy:", np.mean(cv_scores))
print("Std Dev:", np.std(cv_scores))

CV Scores: [0.75 1.   1.   1.   1.  ]
Mean CV Accuracy: 0.95
Std Dev: 0.09999999999999999


Mean of CV scores → average performance → how well model generalizes overall

Standard deviation → shows stability:

Low std → model performs similarly across different splits → stable

High std → model performance depends too much on how data is split → unstable

In [33]:
#Step 7 — Overfitting / Underfitting Check
# Training accuracy
y_train_pred = model.predict(X_train_scaled)
train_accuracy = accuracy_score(y_train, y_train_pred)
test_accuracy = accuracy_score(y_test, y_pred)

print("Training Accuracy:", train_accuracy)
print("Test Accuracy:", test_accuracy)

Training Accuracy: 1.0
Test Accuracy: 1.0


In [35]:
#Compare With Decision Tree
from sklearn.tree import DecisionTreeClassifier

dt_model = DecisionTreeClassifier(random_state=42)
dt_model.fit(X_train, y_train)
y_pred_dt = dt_model.predict(X_test)

print("Decision Tree Accuracy:", accuracy_score(y_test, y_pred_dt))
print("Precision:", precision_score(y_test, y_pred_dt))
print("Recall:", recall_score(y_test, y_pred_dt))
print("F1 Score:", f1_score(y_test, y_pred_dt))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred_dt))

Decision Tree Accuracy: 0.75
Precision: 0.6666666666666666
Recall: 1.0
F1 Score: 0.8
Confusion Matrix:
 [[1 1]
 [0 2]]
